<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\extern\ARIEC61850\src\AR.Iec61850.Transports.Npcap\AR.Iec61850.Transports.Npcap.csproj" />
    <ProjectReference Include="..\..\extern\ARIEC61850\src\AR.Iec61850\AR.Iec61850.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
      <AssemblyName>ARSVIN</AssemblyName>
    <RootNamespace>ARSVIN.App</RootNamespace>
    <Company>Mas Ari</Company>
    <Product>ARSVIN - SV Injector</Product>
    <Description>IEC 61850 Sampled Values manual, ramp, and state sequencer injector.</Description>
    <Copyright>Copyright © Mas Ari</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

</Project>
