<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <RepositoryUrl>https://github.com/masarray/arsvin</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Authors>Ari Sulistiono</Authors>
    <Company>Ari Sulistiono</Company>
    <Copyright>Copyright © 2026 Ari Sulistiono</Copyright>
  </PropertyGroup>
</Project>
